export const SCHOOL_KOREAN_NAME: Record<string, string> = {
  SNU: "서울대",
  YONSEI: "연세대",
  KOREA: "고려대",
  SOGANG: "서강대",
  SKKU: "성균관대",
  HANYANG: "한양대",
  CAU: "중앙대",
  KHU: "경희대",
  HUFS: "한국외대",
  UOS: "서울시립대",
  KONKUK: "건국대",
  DGU: "동국대",
  HONGIK: "홍익대",
  CNU: "충남대",
  CHUNGBUK: "충북대",
  DKU_CHEONAN: "단국대 천안캠",
  SCH: "순천향대",
  HOSEO: "호서대",
  BAEKSEOK: "백석대",
  SUNMOON: "선문대",
};
